# Generated by Django 4.2.7 on 2023-11-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biasharaapp', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
