# Generated by Django 4.2.7 on 2023-11-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biasharaapp', '0003_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
