# Generated by Django 4.2.7 on 2023-11-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasharaapp', '0004_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='Kenya', max_length=50),
        ),
    ]
